### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by okor** [thumbor/thumbor-plugins#10]
Having some trouble getting started developing plugins here. I would greatly appreciate some docs/notes on how to get up and running.

I have an instance of Thumbor locally, not sure if it's required .. but that's done. Thanks

**Comment by guilhermef** [comment]
Hey @okor 
to start developing,
you need to clone the repo and run
````
make setup
```
That will install the project and the last version of Thumbor.

after that you can run:
```
make test 
```
to test if everything is ok,
And on your thumbor.conf you will need to add the plugins you want, something like this:
```
OPTIMIZERS = [
    'thumbor.optimizers.jpegtran',
    'thumbor.optimizers.gifv',
    'thumbor_plugins.optimizers.pngcrush'
]
```

I'll add some docs tomorrow.

**Comment by okor** [comment]
Thanks! I'm good to go. Should have some PR's soon.

One question though. I've created a fork and branch to implement a j2k encoder as an optimizer: https://github.com/okor/thumbor-plugins/commit/39421ed6d9e1f6243dfa0a5f53958c39fd659fc5

But the tests are failing due to a lack of a request attribute in the optimizers context. Previous optimizers only used the image extension as a hook for deciding whether to run the optimizer or not. This is will not work for j2k. Honestly, it feels a bit dirty to even put the j2k encoder in an optimizer to begin with ... because it's not an optimizer it's an encoder. But, that's what has been decided. So, how I can get a request attribute in the optimizer context?

**Comment by guilhermef** [comment]
You can add a request to your test context, like this:
https://github.com/thumbor/thumbor/blob/master/thumbor/handlers/imaging.py#L44

I saw that Pillow also supports jpeg2000: http://pillow.readthedocs.org/en/latest/handbook/image-file-formats.html#jpeg-2000

**Comment by heynemann** [comment]
@okor I'm sorry if this whole implementation is looking a little clumsy on our side. We really would like to have support for as many formats as possible.

That said, we already discussed in a different issue having a proper way of adding support for input and output formats to thumbor. We just do not have a standardized way of doing it. Right now we are doing it with filters/optimizers. 

I do agree with you it's not a filter or an optmizer. If we had the formats standard well defined, I think that would be a better abstraction for it.

Again, sorry and thanks for your effort to keep collaborating.
