### ISSUE TITLE
Please add a release version

### ISSUE THREAD

**Issue by fmunteanu** [thumbor/thumbor-plugins#18]
Adding a version release will allow to properly package the plugins as distribution rpms.

**Comment by fmunteanu** [comment]
Hi @guilhermef, I was wondering if you could take two minutes and at a versioning tag to the project, so I can package the plugins ass RPM.

**Comment by guilhermef** [comment]
Sure, I'll do it tonight.
Em seg, 1 de mai de 2017 às 11:07, Floren Munteanu <notifications@github.com>
escreveu:

**Comment by fmunteanu** [comment]
Hi @guilhermef, not sure if you could look into it this weekend. I would like to build the rpm Monday. :D

**Comment by guilhermef** [comment]
@fmunteanu I'm deeply sorry about the delay, I'm gonna do it now.

**Comment by guilhermef** [comment]
@fmunteanu I've released new version, but the tests are failing.
Is that ok ?

**Comment by fmunteanu** [comment]
Should be fine. :)

**Comment by Enalmada** [comment]
I want to thank anyone who has spent time creating and maintaining thumbor-plugins.  I have just setup thumbor with some of them and am really grateful for your amazing contribution to the community.

**Comment by bagipriyank** [comment]
should this issue be closed now?
