### ISSUE TITLE
using filters:format(jp2) increases the file size considerably

### ISSUE THREAD

**Issue by bagipriyank** [thumbor/thumbor-plugins#22]
I installed openjpeg v2.0.1 as mentioned, added thumbor_plugins to my docker container built using https://github.com/APSL/docker-thumbor. I am testing it locally on my mac laptop, and I am observing that converting a 420KB jpeg file to jp2 is resulting into a 1.6MB file. I tried it with another files, and obtained similar increase in file sizes. I tried changing the JP2_QUALITY environment variable, and that didn't change anything as if it had no effect. The only optimizer I am using is thumbor_plugins.optimizers.jp2. I had tried using jpegtran with jp2 and didn't see any change from above behavior. the docker container was loading libjasper-dev so I removed that in order to create any confusion with openjpeg. I also loaded the libs again and still observed the same behavior. I am using thumbor.engines.pil. I was expecting reduction in file sizes.

**Comment by bagipriyank** [comment]
I tried doing exactly what is done at https://github.com/thumbor/thumbor-plugins/blob/master/thumbor_plugins/optimizers/jp2.py#L28

`
root@ed06bedd997a:~# python
Python 2.7.14 (default, Dec 12 2017, 16:55:09)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.open('/usr/src/app/image.jpg').save('/usr/src/app/image.jp2', 'JPEG2000', quality_mode='80')
>>> exit()
root@ed06bedd997a:~# ls -lh
total 2.2M
-rw-r--r-- 1 root root 1.7M May 25 18:42 image.jp2
-rw-r--r-- 1 root root 424K May 25 18:40 image.jpg
`

**Comment by bagipriyank** [comment]
from http://pillow.readthedocs.io/en/5.1.x/handbook/image-file-formats.html#jpeg-2000

> **quality_mode**
Either “rates” or “dB” depending on the units you want to use to specify image quality.

> **quality_layers**
A sequence of numbers, each of which represents either an approximate size reduction (if quality mode is “rates”) or a signal to noise ratio value in decibels. If not specified, defaults to a single layer of full quality.

```
Image.open('/usr/src/app/image.jpg').save('/usr/src/app/image.jp2', format='JPEG2000', quality_mode='dB', quality_layers=[41,41,41,41])
``` 
produced a 136KB image which looks almost same as the original 420KB jpeg image.

**Comment by bagipriyank** [comment]
@guilhermef i have created a pr (https://github.com/thumbor/thumbor-plugins/pull/23) to resolve the issue. it fixes the build as well. would be great if we can merge it, and create a new release version.

**Comment by guilhermef** [comment]
@bagipriyank, thanks for the PR, it's released on: https://pypi.org/project/thumbor-plugins/0.2.1/
