### ISSUE TITLE
Turn jpeg-recompress into filter?

### ISSUE THREAD

**Issue by estahn** [thumbor/thumbor-plugins#7]
@heynemann jpeg-recompress works fine. It reduces images from 96kb to 17kb (ms-sim algortihm) usually with not much distortion. It seems like the algorithm to be used depends on the image size or certain criteria. It would be great to be able to pass in parameters through the URL or disable the optimiser. Unfortunately optimiser are not part of the so called `filters`. Also if we implement `jpeg-recompress` as filter the final result might be influenced by the `quality` filter after jpeg-compress has been applied.

Any idea how this could be solved?

**Comment by heynemann** [comment]
I wonder if it's practical to pass parameters using the URL for this purpose. It seems to me it's a logic better handled at the optimizer level.

That's why we created the method that allows you to say whether the optimizer should run or not.
